import time
print("Leon dat ben ik")
time.sleep(1)
print("een grote slimerik")
time.sleep(1)
print("komt uit avenhorn")
time.sleep(1)
print("geboren in hoorn")
time.sleep(1)
print("dit is een korte limerick\n")
time.sleep(3)
print("gamen doe ik graag")
time.sleep(1)
print("maar dat eindigt vaak in een nederlaag")
time.sleep(1)
print("zit liever op mijn console")
time.sleep(1)
print("inplaats van gaan naar school")
time.sleep(1)
print("en dit is hoe ik deze limerick wegvaag")
import os

os.system('cls')